<?php include 'header.php';

$product_type = $_GET['type'];
$product_id   = $_GET['id'];

//var_dump($_SESSION);
?>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script src="https://pagination.js.org/dist/2.1.4/pagination.min.js"></script>
	<link rel="stylesheet" href="https://pagination.js.org/dist/2.1.4/pagination.css" />
	<script type="text/javascript" src="//code.jquery.com/ui/1.8.18/jquery-ui.min.js"></script>
	<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css">
	<style>
	.velaProBlock.grid .btnProduct {
		width: 45px;
		height: 45px;
		text-align: center;
		line-height: 48px;
		padding: 20%;
	}

	.sidebarListCategories li.sidebarCateItem {
		display: block !important;
	}

	.paginationjs .paginationjs-pages li.active>a {
		z-index: 3;
		color: #fff;
		background-color: #ba933e;
		border-color: #ba933e;
		cursor: default;
	}

	.paginationjs .paginationjs-pages li:not(:last-child) {
		margin-right: 8px;
	}

	.paginationjs .paginationjs-pages li {
		border-right: 1px solid #aaa !important;
		border: 1px solid #aaa !important;
	}

	.paginationjs .paginationjs-pages li>a {
		font-size: 18px;
	}

	.product-card__image .product-card__img {
		object-fit: cover;
	}
	</style>
	<div class="menuMobileOverlay hidden-md hidden-lg"></div>
	</div>
    <main class="mainContent" role="main">
        <div class="shopify-policy__container">
                    <div class="shopify-policy__title">
                        <h1 style="text-align:center">Privacy Policy</h1>
                    </div>
            <div class="shopify-policy__body">
                <div class="container">

                    <div class="row">
                        <div class="center">
                        <div class="card">
                            <div class="col-md-12" >
                                <div class="rte" >
                                    <span>
                                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the website  <a href="https://www.yosshitaneha.com">https://www.yosshitaneha.com</a>  (hereinafter referred to as the “website”). This electric record is generated by a mobile phone and does not require any physical or digital signatures.
                                    </span>
                                    <br> <br>
                                    <span>
                                        This Privacy Policy is applicable to persons who purchase any product or services from Yosshita & Neha Fashion Studio through any Sales Channel of Sri Shringarr Fashion Studio (like website, mobile site, mobile app, and telephonic order & offline channels). This Privacy Policy also applies to persons who visit the Sri Shringarr Fashion Studio’s offices. As a user or customer of Yosshita & Neha Fashion Studio, the person agrees with this Privacy Policy and the terms and conditions mentioned herein.
                                    </span>
                                    <br> <br>
                                    <span>
                                        This privacy statement does not apply to the websites, mobile sites and mobile apps of our other third parties, even if their websites / apps are linked to Yosshita & Neha Fashion Studio Website. We recommend you review the privacy statements of the other parties with whom you interact. ‘Personal Information’ means and includes all information that can be linked to a specific individual or to identify any individual, such as name, address, mailing address, telephone number, email address, credit card number, cardholder name, expiration date, information about the apparel, bookings and any and all details that may be necessary from the customer. When you visit Yosshita & Neha Fashion Studio’s Website, we may collect information regarding the domain and host from which you access the internet, the internet protocol address of the computer or internet service provider you are using, and anonymous statistical data. The website and mobile site uses cookie and tracking technology depending on the features offered. Personal Information will not be collected via cookies and other tracking technology; however, if you previously provided personally identifiable information, cookies may be tied to such information.
                                    </span>
                                    <span>
                                        When browsing our Website, you are not required to provide any Personal Information unless and until you choose to make a purchase or sign up for one of our e-mail newsletters or other services as described below.
                                    </span>

                                    <h4> SELLING A PRODUCT </h4>

                                    <span>
                                        In order to book a product and/or related services through our Website, you must provide us with certain Personal Information such as your name, credit card number and expiration date, credit card billing address, telephone number, e - mail address and the name or names of the customers buying the product (if not you). We may also ask you for other Personal Information, such as your date of birth or anniversary etc. We require this information to process, fulfill and confirm details of your transactions and keep you informed of each transaction's status.
                                    </span>

                                    <h4> PROMOTIONS & OFFERS</h4>

                                    <span>
                                        Yosshita & Neha Fashion Studio frequently gives out offers to give registered and unregistered members the opportunity to win great discounts and vouchers. Information collected by us for such activities may include contact information and survey questions. We use contact information to notify contest winners and survey information to develop promotions and product improvements. As a member, you will also occasionally receive updates from us about offers in your area, special offers, new Yosshita & Neha Fashion Studio services, and other noteworthy items (like savings and benefits on new dresses, Gala Event packages and other services). In addition, you may look forward to receiving monthly newsletters and exclusive promotions offering special deals. However, you may choose at any time to no longer receive these types of e - mail messages.
                                    </span>
                                    <br><br>
                                    <ol>
                                        <li>
                                            <h4> Collection of Personally Identifiable Information and other Information </h4>
                                            <span>
                                                When you use our Website, we collect and store your personal information which is provided by you from time to time. Our primary goal in doing so is to provide you a safe, efficient, smooth and customized experience. This allows us to provide services and features that most likely meet your needs, and to customize our Website to make your experience safer and easier. More importantly, while doing so we collect personal information from you that we consider necessary for achieving this purpose.
                                            </span>
                                            <br><br>
                                            <span>
                                                In general, you can browse the Website without telling us who you are or revealing any personal information about yourself. Once you give us your personal information, you are not anonymous to us. Where possible, we indicate which fields are required and which fields are optional. You always have the option to not provide information by choosing not to use a particular service or feature on the Website. We may automatically track certain information about you based upon your behavior on our Website. We use this information to do internal research on our users' demographics, interests, and behavior to better understand, protect and serve our users. This information is compiled and analyzed on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our Website or not), which URL you next go to (whether this URL is on our Website or not), your computer browser information, and your IP address.
                                            </span>
                                            <br><br>
                                            <span>
                                                We use data collection devices such as "cookies" on certain pages of the Website to help analyses our web page flow, measure promotional effectiveness, and promote trust and safety. "Cookies" are small files placed on your hard drive that assist us in providing our services. We offer certain features that are only available through the use of a "cookie".
                                            </span>
                                            <br><br>
                                            <span>
                                                We also use cookies to allow you to enter your password less frequently during a session. Cookies can also help us provide information that is targeted to your interests. Most cookies are "session cookies," meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline our cookies if your browser permits, although in that case you may not be able to use certain features on the Website and you may be required to re-enter your password more frequently during a session.
                                            </span>
                                            <br><br>
                                            <span>
                                                Additionally, you may encounter "cookies" or other similar devices on certain pages of the Website that are placed by third parties. We do not control the use of cookies by third parties.
                                            </span>
                                            <br><br>
                                            <span>
                                                If you choose to buy on the Website, we collect information about your buying behavior.
                                            </span>
                                            <br><br>
                                            <span>
                                                If you transact with us, we collect some additional information, such as a billing address, a credit / debit card number and a credit / debit card expiration date and/ or other payment instrument details and tracking information from cheques or money orders.
                                            </span>
                                            <br><br>
                                            <span>
                                                If you choose to post messages on our message boards, chat rooms or other message areas or leave feedback, we will collect that information you provide to us. We retain this information as necessary to resolve disputes, provide customer support and troubleshoot problems as permitted by law.
                                            </span>
                                            <br><br>
                                            <span>
                                                If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on the Website, we may collect such information into a file specific to you.
                                            </span>
                                            <br><br>
                                            <span>
                                                We collect personally identifiable information (email address, name, phone number, credit card / debit card / other payment instrument details, etc.) from you when you set up a free account with us. While you can browse some sections of our Website without being a registered member, certain activities (such as placing an order) do require registration. We do use your contact information to send you offers based on your previous orders and your interests.
                                            </span>
                                        </li>
                                        <li>
                                            <h4> Use of Your Information /Demographic / Profile Data  </h4>
                                            <span>
                                                We use personal information to provide the services you request. To the extent, we use your personal information to market to you; we will provide you the ability to opt-out of such uses. We use your personal information to resolve disputes; troubleshoot problems; help promote a safe service; collect money; measure consumer interest in our products and services, inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection.
                                            </span>
                                            <br><br>
                                            <span>
                                                In our efforts to continually improve our product and service offerings, we collect and analyses demographic and profile data about our users' activity on our Website.
                                            </span>
                                            <br><br>
                                            <span>
                                                We identify and use your IP address to help diagnose problems with our server, and to administer our Website. Your IP address is also used to help identify you and to gather broad demographic information.
                                            </span>
                                            <br><br>
                                            <span>
                                                We will occasionally ask you to complete optional online surveys. These surveys may ask you for contact information and demographic information (like zip code, age, or income level). We use this data to tailor your experience at our Website, providing you with content that we think you might be interested in and to display content according to your preferences.
                                            </span>

                                        </li>
                                            <h4> Cookies </h4>
                                            <span>
                                                A "cookie" is a small piece of information stored by a web server on a web browser so it can be later read back from that browser. Cookies are useful for enabling the browser to remember information specific to a given user. We place both permanent and temporary cookies in your computer's hard drive. The cookies do not contain any of your personally identifiable information.
                                            </span>
                                        <li>
                                            <h4> Sharing of personal info </h4>
                                            <span>
                                                We may share personal information with our other corporate entities and affiliates. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt-out.
                                            </span>
                                            <br><br>
                                            <span>
                                                We may disclose personal information to third parties. This disclosure may be required for us to provide you access to our Services, to comply with our legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our Services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.
                                            </span>
                                            <br><br>
                                            <span>
                                                We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.
                                            </span>
                                            <br><br>
                                            <span>
                                                We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.
                                            </span>
                                        </li>

                                        <li>
                                            <h4> Security Precautions </h4>
                                            <span>
                                                Our Website has stringent security measures in place to protect the loss, misuse, and alteration of the information under our control. Whenever you change or access your account information, we offer the use of a secure server. Once your information is in our possession we adhere to strict security guidelines, protecting it against unauthorized access.
                                            </span>
                                        </li>

                                        <li>
                                            <h4> Third Party Links </h4>
                                            <span>
                                                Our Website links to other websites that may collect personally identifiable information about you. Yosshitaneha.com is not responsible for the privacy practices or the content of those linked websites.
                                            </span>
                                        </li>

                                        <li>
                                            <h4> Choice of Opting-Out </h4>
                                            <span>
                                                We provide all users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us on behalf of our partners, and from us in general, after setting up an account.
                                            </span>
                                            <br><br>
                                            <span>
                                                If you want to remove your contact information from all flipkart.com lists and newsletters, please visit unsubscribe.
                                            </span>
                                        </li>

                                        <li>
                                            <h4> Ads on Yosshitaneha.com </h4>
                                            <span>
                                                We use third-party advertising companies to serve ads when you visit our Website. These companies may use information (not including your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.
                                            </span>
                                        </li>

                                        <li>
                                            <h4> Your Consent </h4>
                                            <span>
                                                By using the Website and/ or by providing your information, you consent to the collection and use of the information you disclose on the Website in accordance with this Privacy Policy, including but not limited to your consent for sharing your information as per this privacy policy.
                                            </span>
                                            <br><br>
                                            <span>
                                                If we decide to change our privacy policy, we will post those changes on this page so that you are always aware of what information we collect, how we use it, and under what circumstances we disclose it.
                                            </span>
                                            <br><br>
                                            <span>
                                                We review our Privacy Policy from time to time, and we may make periodic changes to the policy in connection with that review. Therefore, you may wish to bookmark this page and/or periodically review this page to make sure you have the latest version.
                                            </span>
                                            <span>
                                                You may always submit concerns regarding this Privacy Policy via email to <a href="yosshita.neha@gmail.com"> <b>yosshita.neha@gmail.com</b></a> Yosshita & Neha Fashion Studio will respond to all reasonable concerns or inquiries.
                                            </span>
                                        </li>
                                    </ol>
                                    <h4> Grievance Officer </h4>
                                    <span>
                                        In accordance in accordance with Information Technology Act 2000 and rules made there under, the contact details of the Grievance Officer are provided below:
                                    </span>
                                    <br><br>
                                    <span>
                                        Shyamkamal Building B-1,<br>
                                        Flat No. 104, 1st Floor,<br>
                                        Agarwal Market,<br>
                                        Near Deenanath Mangeshkar Natya Mandir,<br>
                                        Vile Parle East, Mumbai – 400057 <br>
                                        Mobile No.: 09324243011 / 07400413163 <br>
                                        Email: <a href="yosshita.neha@gmail.com">yosshita.neha@gmail.com</a> <br>
                                        Time: Available from Tuesday – Sunday (12:00 – 19:00) Website Use.

                                    </span>
                                    <br><br>
                                    <span>
                                        The Website User shall at all times while accessing, uploading and/ or using the services of this Website shall abide by the following principles :
                                    </span>
                                    <br><br>
                                    <ul>
                                        <li>
                                            <span>
                                                Website User shall not host, display, upload, modify, publish, transmit, update or share any information, including but not limited to, content, image or graphic, which:
                                            </span>
                                        </li>
                                        <ul>
                                            <li>
                                                <span>
                                                    belongs to another person and to which the Website User does not have any right to
                                                </span>
                                            </li>

                                            <li>
                                                <span>
                                                    is grossly false, inaccurate, harmful, harassing, abusive, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing in any manner, whatsoever
                                                </span>
                                            </li>

                                            <li>
                                                <span>
                                                    is misleading or harms minors in any way
                                                </span>
                                            </li>
                                            <li>
                                                 <span>
                                                    contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page)
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    provides information violating someone's privacy, or provides or creates computer viruses
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    contains video, photographs, or images of another person, without that person’s consent; impersonates another person
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    is patently offensive to the online community, such as sexually explicit content or provides material that is violent or otherwise inappropriate or solicits personal information from anyone or provides content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    interferes with another Website User's use and enjoyment of this Website or refers to any other website or URL, that in Website Owner’s sole discretion, contains material that is inappropriate for this Website or any other website, contains content which is prohibited or violates the letter or spirit of these Terms of Use.
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    violates any law for the time being in force
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    deceives or misleads the addressee and/ or other Website Users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting for any other nation.
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    infringes upon or violates any third party's rights, including, but not limited to, intellectual property rights, which includes patents, trademarks, copyrights or other proprietary rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    The Website User shall not create liability for the Website Owner or cause the Website Owner to lose (in whole or in part) the services of Website Owner’s internet service provider ("ISPs") or other suppliers;
                                                </span>
                                            </li>
                                            <li>
                                                <span>
                                                    The Website User shall at all times abide by the requirements of the Information Technology Act, 2000 (hereafter referred to as the “IT Act”) and the rules, regulations, policies, guidelines, bye laws and notifications made thereunder and/ or any law which is applicable for the time being in force while uploading any content, accessing, or using the services offered by this Website. The Website User shall unequivocally declare that in case of violation of any of the provisions of the IT Act and/ or rules, regulations, bye-laws, policies, guidelines and notifications made thereunder and/ or any law which is applicable for the time being in force, the Website User shall be solely responsible at his/ her own costs for all acts, deeds and things and the Website User shall be liable for any kind of civil or criminal liability there under.
                                                </span>
                                            </li>

                                        </ul>

                                    </ul>

                                    <h4> INDEMNITY </h4>
                                    <span>
                                        The Website User shall indemnify the Website Owner, its subsidiaries, representatives, affiliates, assigns, group companies, employees, directors, agents and officers against all the liabilities arising out of the use of this Website and/ or any claims, demands, expenses, liabilities (including statutory liability), penalties, damages (including but not limited to, compensatory, direct, incidental or consequential), awards, losses, costs (including, but not limited to, legal fees) or actions arising out of any applicable law or the breach or nonperformance of any of the provisions of these Terms of Use or any of the Policies by which this Website is governed, including but not limited to Privacy Policy, Intellectual Property Policy, Return and Cancellation Policy or due to hacking/ lapse in the security of this Website.
                                    </span>

                                    <h4> INTELLECTUAL PROPERTY </h4>
                                    <span>
                                        Any information/ material/ images which are available on this Website are solely for the personal and non-commercial use of the Website User. The Website User shall not copy, reproduce, republish, upload, post, transmit, misuse or distribute such material in any way, including by email or other electronic means or assist directly or indirectly other person for any purpose, including but not limited to, for their personal gain. Without the prior written consent of the Website Owner, modification and/ or use of the information available on this Website on any other Website or website or networked computer environment or use of the information/ material/ images for any purpose, whatsoever, is a violation of the Intellectual property rights of the Website Owner and is strictly prohibited. The Website User acknowledges and agrees not to register, use or file in his/ her own name or in the name of any other person or Company any intellectual property, including but not limited to trademarks, which is same or similar or resembling, in any manner and not to associate the same with his/ her own business or any other business, except for the purpose and in the manner as specified in these Terms of Use and all the Policies available on this Website. The Website User agrees and acknowledges that the Intellectual Property available on this Website is the rightful and sole property of the Website Owner. In this regard, Intellectual Property shall include but is not limited to, name, signature, brand name, word, letter, numeral or combination thereof, trademark, service mark, trade name, copyright, design, logo, know-how, trade secrets, photographs/ images, whether registered or not. Any use for which the Website User receives any remuneration, whether in money or otherwise, is a commercial use for the purpose of this clause and commercial use of the Intellectual Property belonging to the Website Owner and/ or available on this Website is strictly prohibited.
                                    </span>

                                    <h4> CONFIDENTIALITY </h4>
                                    <span>
                                        The Website User hereby agrees that he/ she shall not disclose to any third party any trade secret or confidential information pertaining to this Website, including but not limited to, services offered, products available, Website content and transaction undertaken on this Website. The provisions of the Privacy Policy of this Website shall apply in case of breach of this clause.
                                    </span>

                                    <h4> LIMITATION OF LIABILITY </h4>
                                    <span>
                                        In no case, shall the Website Owner be liable for any special, direct, indirect, incidental or consequential damages of any kind in connection with the usage or anything which is available on this Website. Notwithstanding anything, which is stated in these Terms of Use and all other policies available on this Website, in the unlikely and rare scenario, the Website User hereby acknowledges that in any event, the Website Owner’s aggregate liability with respect to the service and/ or usage of this Website shall be limited to and not exceed, the sum equivalent to the Sale Price of the single and the most recent transaction undertaken by him/ her on this Website and shall be as per these Terms of Use (excluding the Delivery Charges and/ or any other extra charges, if any).
                                    </span>

                                    <h4> Miscellaneous Provisions </h4>
                                    <span>
                                        If the Website User does not agree to any of the provisions of these Terms of Use and/ or the provisions of the other Policies available on this Website, including but not limited to, Privacy Policy, Intellectual Property Policy, Return and Cancellation Policy, then the only remedy with him/ her shall be to not use/ access this Website and discontinue using the account made on this Website.
                                    </span>
                                    <br><br>
                                    <span>
                                        The Website Owner acknowledges and agrees that he/ she abides and is well aware of all the provisions of these Terms of Use and all the Policies available on this Website , including but not limited to, Privacy Policy, Intellectual Property Policy, Return and Cancellation Policy before placing any Order for a product displayed on this Website. The Website Owner is an individual contractor and the Website Owner is in no manner acting as the Website User’s agent.
                                    </span>
                                    <br><br>
                                    <span>
                                        The Website Owner shall not be responsible in any manner, including but not limited to, delay or failure to comply with their obligations arising as per these Terms of Use and/ or other Policies available on this Website, in case of events like acts of God, fire, wars, sabotage, civil unrest, riots, labor unrest, action of Statutory Authorities/ local authorities or State/ Central Government, change in laws/ rules/ regulations and/ or any cause which is beyond the reasonable control of the Website Owner.
                                    </span>
                                    <br><br>
                                    <span>
                                        If the Website User breaches any of the provisions of these Terms of Use and/ or other Policies available on this Website, the Website Owner shall still be entitled to enforce their rights/ remedies arising out of this Terms of Use and/ or other Policies available on this Website.
                                    </span>
                                    <br><br>
                                    <span>
                                        Unless otherwise stated expressly, the delay/ failure by the Website Owner in exercising any right(s)/ remedy (ies) arising out of these Terms of Use and/ or other Policies available on this Website, hereunder, shall not constitute a waiver of right(s) or remedy (ies) and no single/ partial exercise of any right(s) or remedy (ies), hereunder, shall prevent any further exercise of the right(s)/ remedy (ies) by them.
                                    </span>
                                    <br><br>
                                    <span>
                                        If any of the provisions of this Terms of Use or the provisions of the Policies available on this Website, hereunder becomes in whole or in part, invalid or unenforceable, but, the same would be valid and enforceable if some part of that provision which is invalid/ unenforceable is deleted and the remaining provision shall apply with such deletions, that may be necessary to make it valid and enforceable. If any Court/ Tribunal of competent jurisdiction holds any of the provisions of these Terms of Use and/ or provisions of the Policies available on this Website, hereunder invalid or unenforceable, the remainder of the provisions shall remain in force, the unlawful or otherwise ineffective provision shall be substituted by a new provision reflecting the intent of the provision so substituted.
                                    </span>

                                    <h4> You’re Interaction with Us </h4>
                                    <span>
                                        When the Website User uses this Website, or send emails or other data, information or communication to the Website Owner, the Website User agrees and understands that he/ she are communicating with the Website Owner through electronic records and the Website User consents to receive communications via electronic records from the Website Owner periodically and as and when required. The Website Owner may communicate with the Website User by email or by such other mode of communication, electronic or otherwise.
                                    </span>
                                    <br><br>
                                    <span>
                                        All notices, requests, demands, waivers and other communications required or permitted to be given hereunder shall be sent to <a href="hello@yosshitaneha.com"><b>hello@yosshitaneha.com</b></a>, if to the App Owner, if to the App User, it shall be to the email address and/or postal address registered with the App Owner.
                                    </span>

                                    <h3> DISCLAIMER </h3>
                                    <span>
                                        The Website Owner does not guarantee that the Website User will always have an uninterrupted access to this Website and it does not warrant that the information available on this Website is complete, true, accurate and not misleading. Nothing on this Website constitutes or is meant to constitute advice of any kind. The Website Owner will make their best effort to provide an error free and continuously available Website without any dangerous elements being sent to the Website User’s computer, laptop, mobile phone or any other device with which he/ she is using this Website. However, the Website Owner shall not be liable to the Website User in any way, in relation to the content, use, electronic communication sent or otherwise anything in connection with this Website is free from viruses or other harmful components. The Website Owner cannot fully control the internet’s flow of information; it cannot ensure that they do not contain any elements that may harm the Website User’s computer, laptop, mobile phone or any other device with which the Website User is using this Website.
                                    </span>
                                    <br><br>
                                    <span>
                                        The Website Owner may, at its own discretion, at any time without any prior notice, take steps to ensure the security and quality of this Website and restrict or limit the access to this Website.
                                    </span>
                                    <br><br>
                                    <span>
                                        Sri Shringarr Fashion Studio retains the right to alter and amend these terms of use at any time without intimation and the amended Terms of use would be available at the same page for reference.
                                    </span>
                                    <br><br>
                                    <span >
                                        Thank you for using Yosshita & Neha Fashion Studio, Happy Shopping!
                                    </span>
                                    <br><br>
                                    <span>
                                        Sri Shringarr Fashion Studio retains the right to alter and amend these policies at any time without intimation and the amended policy would be available at the same page for reference.
                                    </span>

                                </div>
                            </div>
                        </div>
                    </div>

                    </div>


                </div>

            </div>
        </div>
    </main>
	<style type="text/css">
	@keyframes ldio-kpxe4ypb4vk {
		0% {
			transform: rotate(0deg)
		}
		50% {
			transform: rotate(180deg)
		}
		100% {
			transform: rotate(360deg)
		}
	}

	.ldio-kpxe4ypb4vk div {
		position: absolute;
		animation: ldio-kpxe4ypb4vk 1s linear infinite;
		width: 160px;
		height: 160px;
		top: 20px;
		left: 20px;
		border-radius: 50%;
		box-shadow: 0 4px 0 0 #deb34b;
		transform-origin: 80px 82px;
	}

	.loadingio-spinner-eclipse-w42oo7vkqqq {
		width: 200px;
		height: 200px;
		display: inline-block;
		overflow: hidden;
		/*background: #f1f2f3;*/
	}

	.ldio-kpxe4ypb4vk {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0;
		/* see note above */
	}

	.ldio-kpxe4ypb4vk div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
	</style>
	<div id="q"></div>
	<style>
	.flash {
		display: block;
		position: fixed;
		top: 125px;
		right: 25px;
		width: 350px;
		padding: 20px 25px 20px 85px;
		font-size: 16px;
		font-weight: 400;
		color: #66847C;
		background-color: #FFF;
		border: 2px solid #66847C;
		border-radius: 2px;
		box-shadow: 0 2px 5px rgba(0, 0, 0, 0.25);
		opacity: 0;
		z-index: 100;
		/*display:none;*/
	}

	.flash__icon {
		position: absolute;
		top: 50%;
		left: 0;
		width: 1.8em;
		height: 100%;
		padding: 0 0.4em;
		background-color: #66847C;
		color: #FFF;
		font-size: 36px;
		font-weight: 300;
		transform: translate(0, -50%);
	}

	.flash__icon .icon {
		position: absolute;
		top: 50%;
		transform: translate(0, -50%);
	}

	.button {
		position: absolute;
		top: 50%;
		left: 50%;
		padding: 10px 20px;
		border: 2px solid #66847C;
		border-radius: 2px;
		color: #66847C;
		transform: translate(-50%, -50%);
		transition: all 0.1s;
	}

	.button:hover {
		cursor: pointer;
		color: #FFF;
		background-color: #66847C;
	}

	.button:active {
		box-shadow: none;
		background-color: #5f7b74;
	}

	@-webkit-keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	@-moz-keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	@-o-keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	@keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	.animate--drop-in-fade-out {
		-webkit-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		-moz-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		-ms-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		-o-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
	}
	</style>
	<?php include 'footer.php';?>