<?php session_start();
include("access.php");
include('config.php');
//include('functions.php');

include("menubar.php");  
        
?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>New Sales Order </title>
    <link href="style.css" rel="stylesheet" type="text/css" />
    <link href="menu.css" rel="stylesheet" type="text/css" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.4.1.js"
      integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
      crossorigin="anonymous"></script>
      
      <style>
      
      input:focus{
          outline: none;
      }
      .custom_radio{
              width: 5%;
    height: 20px;
      }
      .cust_column{
          display:flex;
      }
      .submit_btn{
          display:flex;
          justify-content:center;
      }
      .submit_btn input{
          width:15%;
          margin:2%;
      }
      
      
      input[type="text"]{
          width:100%;
      }
      .optional_input, .hide{
    display: none;
}

.show {
    display: block ! important;
}
           html[xmlns] #menu-bar {
    display: block;
    z-index: 1000;
    position: relative;
}
#menu-bar li:hover > ul {
    text-align: center;
}

#menu-bar{
        width: 100%;
}
   
   body{
           background-color: #4D9494;
    margin-top: 20px;
    
   }
   #custer_vertical, #po_no{
       width:100%;
   }

   .additional_buttons{
       display: flex;
    justify-content: center;

   }
   .additional_buttons form{
       margin:1%;
   }
   .custom_row label{
       display:block;
           font-size: 18px;
   }
   .row{
       margin:2%;
   }
   label{
       color:white;
   }
    html[xmlns] #menu-bar {
    display: block;
    z-index: 1000;
    position: relative;
}
#menu-bar ul{
    z-index: 999;
}
table{
    width: 50% !important;
    margin: auto;
}

/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}

#check_partial_product ,#check_all_product{
    border: 0;
    border-radius: 0;
    box-shadow: none;
}
input[type=checkbox]{
        height: 20px;
    width: 20px;
    margin: 0;
}
#po_qty{
        background-color: transparent;
    border: none;
        text-align: center;
    width: 100%;
}
      </style>
    </head>
    
               <div class="search_fields" style="margin: 1%;">
                    
                    <form class="form-inline" method="POST">    
                        
                    <div class="form-group col-md-2">
                    <label for="mailid" class="sr-only">emails for auto message</label>
                    <input type="text"  class="form-control" id="mailid" name="mailid" placeholder="emails">
                    </div>
                    
                    <div class="form-group col-md-2">
                    <label for="subject" class="sr-only">Copy Subjet Line</label>
                    <input type="text"  class="form-control" id="subject" name="subject" placeholder="subject">
                    </div>
                    
                    <input class="btn btn-success" type="submit" name="search" value="Send">
                    
                    </form>
                </div>
           
           
           <?
           $mailid = $_POST['mailid'];
           $sub = $_POST['subject'];
           
function extract_email_address($string) {
    foreach(preg_split('/\s/', $string) as $token) {
        $email = filter_var(filter_var($token, FILTER_SANITIZE_EMAIL), FILTER_VALIDATE_EMAIL);
        if ($email !== false) {
            $emails[] = "<".$email.">";
        }
    }
    return $emails;
}           
           if($mailid){
               
$tbl="<html>
<head>
<title>Switching AVO Electro Power Limited</title>
</head>
<body>
<table border='1' width='700px'>
<tr>
	<td>Hello AVO Helpdesk !! <br>
	Sorry ! I Can't Generate the call. Speak to the Account Manager First.
	<br><br>Dear Customer !! <br>
	We are very much regret that the calls can not be generated by the system as the site was deactivated automatically. Please check whether the site is under AMC or Warranty or whether the valid PO is provided. <br><br>
	
	You are requested to contact the concern acccount manager for further assistant or support on this!! <br> <br>
	
	This is system generated mail and hence no need to respond on this by mail

	</td>
	
</tr>";

	$to = "service3@avoups.com";
	$ccm=implode(",",extract_email_address($mailid));
	$ccm=str_replace("<","",$ccm);
    $cc=str_replace(">","",$ccm);
	
	$subject = "Oops !! Something Went Wrong !! ".$sub ;
	$tbl.="</table><br><br><font color='blue'>Switching <font color='red'>AVO</font> Electro Power Limited</font> 
			<br><br><font color='red'>".$_SESSION['user']."</font> </body></html>";
	$headers = "From:<system_admin@avoservice.in>\r\n";
	$headers .= "MIME-Version: 1.0\r\n";
	$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
	$headers .= "Cc: ".$cc. "\r\n";
	$message=$tbl;
	$mailqry=mail($to, $subject, $message, $headers);
	
if($mailqry) { echo "Mail Sent Successfully";
            } else echo "Sorry, Some issue";
            
           }

           ?>     
    </body>
      
      </html>  