"""
Django settings for Ecom project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6gt+fxq))f6)a(+fa7--mkl@))+dk!2zu8b^l_7u1w_5gq*(9f'

API_SECRET_KEY  = '6krV*eJaJzHw#UgD'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AUTH_USER_MODEL = 'ecomauth.userDetails'

ALLOWED_HOSTS = ['*']

PAYU_INFO = {
     #'merchant_key': "m4jrpW",
     #'merchant_salt': "3Ajm29GJ",
     'merchant_key': "gtKFFx",
     'merchant_salt': "eCwWELxi",
     # for production environment use 'https://secure.payu.in/_payment' and for test use 'https://test.payu.in/_payment'
     'payment_url': 'https://test.payu.in/_payment',
     'success_url':'http://127.0.0.1:8000/payment/success/',
     'failuer_url':'http://127.0.0.1:8000/payment/failure/',
    }


# Application definition

INSTALLED_APPS = [
    'mainapp.apps.MainappConfig',
    'ecomauth.apps.EcomauthConfig',
    'ecomadmin.apps.EcomadminConfig',
    'ecomsite.apps.EcomsiteConfig',
    'tinymce',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/var/www/vhosts/srishringarr.com/Ecom/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'srishrin_srishringarr9623',
        'USER' : 'srishrin_sri1654',
        'PASSWORD' : 'n#QnM~.}J^}y'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_PATH = os.path.join(BASE_DIR ,'static')

MEDIA_ROOT = os.path.join(STATIC_PATH)

STATIC_URL = '/static/'

STATICFILES_DIRS = (
   STATIC_PATH,
)

#for live static path
STATIC_DIR_PATH = '/var/www/vhosts/srishringarr.com/Ecom/static/'

#for local static path
# STATIC_DIR_PATH = '/home/shrawan/Ecom/static/'

#tinymce
TINYMCE_DEFAULT_CONFIG = {
    'theme' : 'advanced',
    'theme_advanced_buttons1' : 'bold,italic,underline,strikethrough,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,formatselect,fontselect,fontsizeselect',
    'theme_advanced_buttons2' : 'cut,copy,paste,pastetext,pasteword,separator,bullist,numlist,separator,outdent,indent,blockquote,separator,undo,redo,separator,link,unlink,anchor,image,cleanup,help,code,separator,forecolor,backcolor',
    'theme_advanced_buttons3' : 'sub,sup,separator,hr,charmap,separator,',
    'theme_advanced_toolbar_location' : 'top',
    'theme_advanced_toolbar_align': 'left',
    'paste_text_sticky': True,
    'paste_text_sticky_default' : True,
    'valid_styles' : 'font-weight,font-style,text-decoration',
}

LOGIN_URL= '/login/'

#razorpay credentials
RAZORPAY_INFO = {
    #"api_key":"rzp_live_VryG5brTni7hhU",         #######05-08-19####### Sri Shringarr API KEY ###########
    #"secret_key":"UDvXTRxKjtJRb5PHOaQHJgbH",
    #"api_key":"rzp_live_pQ8S2lyvnOWSg4",          #######05-08-19####### Xircls Api Key ###########
    #"secret_key":"MS60AvhqfEkZFe5PPsGJDnGa",
    "test_api_key":"rzp_test_B3MzUEcuRcfQD2",    #########31-07-19######
    "test_secret_key":"spDW2soiMwgcZLB8AIHAarFi",
}

EMAIL_HOST = 'mail.srishringarr.com'
EMAIL_HOST_USER = 'info@srishringarr.com'
# EMAIL_HOST_PASSWORD = 'Nucleus2018'
EMAIL_HOST_PASSWORD = 'Bhagwati2019**'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


# EMAIL_HOST = 'smtp-relay.sendinblue.com'
# EMAIL_HOST_USER='info@firstnucleus.com'
# EMAIL_HOST_PASSWORD='gxKCQm92sdSMvXnU'
# EMAIL_PORT = 587
# EMAIL_USE_TLS=True

# For RabbitMQ
# BROKER_URL = 'amqp://[inet 101.53.143.58]'
# CELERY_RESULT_BACKEND = 'amqp://[inet 101.53.143.58]'
# Celery Data Format
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Asia/Kolkata'
EMAIL_HOST = 'mail.srishringarr.com'
EMAIL_HOST_USER = 'info@srishringarr.com'
EMAIL_HOST_PASSWORD = 'Bhagwati2019**'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_HOST_USER = 'sushant@nucleusads.com'
# EMAIL_HOST_PASSWORD = 'Nucleus2018'
#EMAIL_HOST_PASSWORD = 'nnheujzshtjpajbj'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"