<?php include 'header.php';

$product_type = $_GET['type'];
$product_id   = $_GET['id'];

//var_dump($_SESSION);
?>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script src="https://pagination.js.org/dist/2.1.4/pagination.min.js"></script>
	<link rel="stylesheet" href="https://pagination.js.org/dist/2.1.4/pagination.css" />
	<script type="text/javascript" src="//code.jquery.com/ui/1.8.18/jquery-ui.min.js"></script>
	<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css">
	<style>
	.velaProBlock.grid .btnProduct {
		width: 45px;
		height: 45px;
		text-align: center;
		line-height: 48px;
		padding: 20%;
	}

	.sidebarListCategories li.sidebarCateItem {
		display: block !important;
	}

	.paginationjs .paginationjs-pages li.active>a {
		z-index: 3;
		color: #fff;
		background-color: #ba933e;
		border-color: #ba933e;
		cursor: default;
	}

	.paginationjs .paginationjs-pages li:not(:last-child) {
		margin-right: 8px;
	}

	.paginationjs .paginationjs-pages li {
		border-right: 1px solid #aaa !important;
		border: 1px solid #aaa !important;
	}

	.paginationjs .paginationjs-pages li>a {
		font-size: 18px;
	}

	.product-card__image .product-card__img {
		object-fit: cover;
	}
	</style>
	<div class="menuMobileOverlay hidden-md hidden-lg"></div>
	</div>
    <main class="mainContent" role="main">
        <div class="shopify-policy__container">
                    <div class="shopify-policy__title">
                        <h1 style="text-align:center">Terms of service</h1>
                    </div>
            <div class="shopify-policy__body">
                <div class="container">

                    <div class="row">
                        <div class="center">
                        <div class="card">
                            <div class="col-md-12" >
                                <div class="rte" >
                                    <span>
                                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the website  <a href="https://www.yosshitaneha.com">https://www.yosshitaneha.com</a>  (hereinafter referred to as the “website”). This electric record is generated by a mobile phone and does not require any physical or digital signatures.
                                    </span>
                                    <br> <br>
                                    <span>
                                        The domain name <a href="https://www.yosshitaneha.com">https://www.yosshitaneha.com</a> (hereinafter referred to as the "website") is owned by Sri Shringarr Fashion Studio, a proprietorship firm located at Shyamkamal Building B-1, Flat No. 104, 1st Floor, Agarwal Market, Near Deenanath Mangeshkar Natya Mandir, Vile Parle East, Mumbai - 400057.
                                    </span>
                                    <br> <br>
                                    <span>
                                        For the purpose of these Terms of Use and including the applicable policies which are incorporated herein by way of reference, wherever the context so requires “Website Owner” and “Website” shall mean Yosshita &Neha Fashion Studio <a href="https://www.yosshitaneha.com">https://www.yosshitaneha.com</a> respectively.
                                    </span>

                                    <h4> Website Content </h4>

                                    <span>
                                        This Website may contain references/ links to Third Party Websites/ Resources, including but not limited to, products, services or other content. The Website User acknowledges that the Owner is not liable in any manner, whatsoever, for any of such content, which includes the availability and/ accuracy of such websites/ resources and the content, products or services offered by such websites/ resources as may be displayed on this Website or that the Website User may be re- directed to while accessing services offered by this Website. It is hereby clarified that the references/ links to such Third-Party Websites/ Resources, which may be displayed on this Website, are not owned, operated or controlled by the Website Owner and it does not imply any endorsement by the Website Owner. The Website Owner shall not be liable for any of the privacy practices of the Third Party Website(s)/ Reference(s).
                                    </span>
                                    <br> <br>
                                    <span>
                                        Any comments, feedback and/ or suggestions posted by the Website User on this Website are the sole and exclusive property of the Website Owner and the Website User assigns unequivocal and irrevocable right, title and interest including but not limited to trade secret, moral, proprietary and other intellectual rights therein, in all the comments, feedback and/ or suggestions posted by him/ her on this Website. The Website User explicitly agrees that the Website Owner has the exclusive discretion to remove any content uploaded by him/ her or restrict the publication of any content on this Website, without assigning any reasons to the Website User. The Website User hereby explicitly agrees that the Website Owner may use the content uploaded by him/ her for any purpose as it may deem fit to the Website Owner, including but not limited to, promotion, advertisement and marketing the services offered by this Website without taking any consent of the Website User and without any payment by the Website Owner in relation to such use to the Website User. It is also clarified that the content uploaded by the Website User shall be in consonance with these Terms of Use.
                                    </span>
                                    <br> <br>
                                    <span>
                                        The Website User is required to provide a valid phone number, credit card/debit card details, accurate and full Shipping Address in order to avail the Services provided by the Website Owner, including and not limited to, placing orders for purchasing the Products displayed on this Website. By registering the phone number with the Website Owner, the Website User consent to be contacted by the Website Owner via phone calls and/or SMS notifications, in case of any Order or shipment or delivery related updates.
                                    </span>
                                    <br><br>
                                    <span>
                                        Content made available on this Website, including but not limited to, images, specification of the products or any comments or reviews of the App User are available on “as is” and “as available” basis and is displayed solely for informational purpose. The content made available on this Website shall not be relied by the Website User as substitutes for professional advice or services. It is hereby clarified that the Website Owner shall have the sole discretion to update, change or modify the content made available on this Website. The Website User exclusively agrees and acknowledges that the Website Owner is not liable for any non-disclosure or incomplete disclosure of any information in relation to the products displayed or the services offered by this Website.
                                    </span>
                                    <br><br>
                                    <span>
                                        All photographs used on this Website are the exclusive property of the Website Owner. The Website Owner has taken reasonable efforts to ensure that the products listed on this Website are authentic and original works of the specified Brand or Designer.
                                    </span>
                                    <br><br>
                                    <span>
                                        The Website User shall not make any negative, defamatory or derogatory comment(s), statement(s), review(s) about the Website Owner, the brand name and/ or the domain name, or otherwise engage in any conduct or action that might tarnish the image, goodwill or the reputation of the Website Owner.
                                    </span>
                                    <h4> USER ELIGIBILITY </h4>

                                    <span>
                                        For the purpose of these Terms of Use and including the applicable policies which are herein by way of reference, wherever the context so requires “User” or “he/ she” or “his/ her” shall mean any natural or legal person who is competent to enter into a legally binding Contract under the “Indian Contract Act, 1872” (hereinafter referred to as the “Contract Act”). Any person who is not competent under the Contract Act to enter into a legally binding Contract including minors, un- discharged insolvents, persons of unsound mind etc. are not eligible to use this website. This website is intended for individuals who are 18 years of age or above. By accessing or using this website or the services rendered by this website in any manner, the Website User warrants that he/ she is 18 years of age or above.
                                    </span>
                                    <br><br>
                                    <span>
                                        Items rendered for sale/ hire on this Website may be used and worn by individuals who are below 18 years of age, but, rentals and all other payments should necessarily be made by persons who are 18 years of age or above. If a Minor (person below 18 years of age) wishes to use or transact on this Website, such use or transaction shall be made by his/ her legal guardian or parents on this Website. The  Website Owner reserves the right to terminate the membership and/ or refuse to provide the  Website User with access to this  Website if it is brought to App Owner's / Website Owner’s notice or if it is discovered that the  Website User is under the age of 18 years or is incompetent to enter into a legally binding Contract according to the provisions of the Contract Act.
                                    </span>
                                    <br><br>
                                    <span>
                                        Any person using the services rendered by this  Website on behalf of any other person/ partnership concern/ proprietorship/ firm/ body corporate/ company, represents and warrants that he/ she is duly authorized by such person/ partnership concern/ proprietorship/ firm/ body corporate/ company being the User to accept these Terms of Use and including the applicable Policies which are incorporated herein by way of reference, that such person has the authority to bind the User to these Terms of Use and including the applicable Policies which are incorporated herein by way of reference.
                                    </span>

                                    <h4> USER ACCOUNT AND REGISTRATION </h4>

                                    <span>
                                        The Website may need not register himself/ herself to navigate through this Website, but, is required to register himself/ herself on this Website by making an Account on this Website, called as the “Yosshita & Neha Fashion Studio Account” for availing all/some of the services provided by this Website, including, but not limited to selling of the products available on this Website. The Website user shall be allowed to rent the products displayed on this Website or avail any of the services provided by this Website, only after registering himself/ herself on this Website.  Website User shall maintain the privacy and confidentiality of the information provided by him/ her for registering himself/ herself on this Website called the “Account Information” including, but not limited to the Display Name and the Password. The Website User shall be solely liable and responsible for the correctness of the Account Information being provided by him/ her.
                                    </span>
                                    <br><br>
                                    <span>
                                        The Website User may also register by logging into his/ her account with a third party social networking Sites, including, but, not limited to Facebook and Instagram. The  Website User may choose to link his/ her Yosshita & Neha Fashion Studio Account with third party accounts, by either Providing  Website User’s third party account information to this  Website on Yosshita & Neha Fashion Studio Account, or Allowing the Website Owner to access the Website User’s third party account on the social networking site, as is permitted under the applicable terms and conditions that govern the  Website User’s use of each of the third party account on the social networking Site.
                                    </span>
                                    <br><br>
                                    <span>
                                        The  Website User represents and warrants that he/ she is entitled to disclose his/ her third party account login information on the social networking site(s) to the  Website Owner including, but not limited to, for the purpose described herein, without breaching any of the conditions that govern the  Website User’s use of the applicable Third Party Account on the social networking site(s) and without making the  Website Owner responsible in any manner, whatsoever. By granting Website Owner the access to any Third-Party Account on the applicable social networking site(s), the Website User understands that the Website Owner will access, make available and store any content that the Website User has provided to and stored in the Website Owner’s Third Party Account on the applicable social networking site(s). Unless otherwise specified in the Terms of Use of this Website, all information provided by the Website User to the Third-Party Account on the applicable social networking Site(s) shall be considered to be information provided by the Website User to this Website for all purposes. Depending on the privacy settings that the Website User has chosen in such Third-Party Account on the applicable social networking Site(s), any personally identifiable information that the Website User posts on such Third-Party Account on the applicable social networking site(s) would be available through the Website User’s Yosshita & Neha Fashion Studio Account. If the Website User’s Third Party Account on the applicable social networking site(s) becomes unavailable or the Website Owner’s access to Website User’s Third Party Account on the applicable social networking site(s) is terminated by the Third Party Account service provider, then in that case the content which was being accessed by the Website Owner through such Third party Account would no longer be available on this Site.
                                    </span>
                                    <br><br>
                                    <span>
                                        The Website User’s relationship with the Third Party Service Provider associated with the Website User’s Third Party Account on the applicable social networking site(s) is solely governed by the Website User’s agreement(s) with such Third Party Service Provider. The Website Owner does not review any of the information provided by the Website User to such Third Party Account on the applicable social networking site(s) for any purpose, including, but not limited to, for accuracy, legality or non-infringement and the Website Owner is not responsible for any information which the Website Owner uses from the Third Party Account.
                                    </span>
                                    <br><br>
                                    <span>
                                        The Website User agrees that if the Website User provides any information which is inaccurate, not current or incomplete or where the Website Owner has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the Terms of Use of this Website then the Website Owner shall have the right to indefinitely suspend or terminate or block access to membership of the Website User on this Website and refuse the Website User access to this Website, without assigning any reason(s), thereof.
                                    </span>

                                    <h4> Legality </h4>
                                    <span>
                                        Terms of Use and all other policies available on this Website shall be interpreted and construed in accordance with the laws of India.
                                    </span>
                                    <br><br>
                                    <span>
                                        Any dispute or claim relating to products available on this Website or the services rendered by this Website, its enforceability or the termination under these Terms of Use and/ or other policies available on this App shall be governed by the Arbitration and Conciliation Act, 1966 by a sole arbitrator, who shall be appointed by the Website Owner. The place of Arbitration shall be Mumbai and the language of proceedings shall be English. The Website User and the Website Owner agree specifically to submit to the exclusive jurisdiction of the Courts of Bombay at Mumbai, India over any disputes relating to the subject matter, herein.
                                    </span>
                                    <br><br>
                                    <span>
                                        Unless, otherwise specified, the products available and the services offered by this Website are solely rendered in India. The Website Owner makes no representation that the products on this Website are for use/ available in any other Country/ location other than India. The Website User may choose to access this Website from any other location, other than India, but, he/ she does this in his/ her sole discretion and the Website Owner shall not be responsible, in any manner, for supply/ delivery of products ordered from locations, other than India.
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    </div>


                </div>

            </div>
        </div>
    </main>
	<style type="text/css">
	@keyframes ldio-kpxe4ypb4vk {
		0% {
			transform: rotate(0deg)
		}
		50% {
			transform: rotate(180deg)
		}
		100% {
			transform: rotate(360deg)
		}
	}

	.ldio-kpxe4ypb4vk div {
		position: absolute;
		animation: ldio-kpxe4ypb4vk 1s linear infinite;
		width: 160px;
		height: 160px;
		top: 20px;
		left: 20px;
		border-radius: 50%;
		box-shadow: 0 4px 0 0 #deb34b;
		transform-origin: 80px 82px;
	}

	.loadingio-spinner-eclipse-w42oo7vkqqq {
		width: 200px;
		height: 200px;
		display: inline-block;
		overflow: hidden;
		/*background: #f1f2f3;*/
	}

	.ldio-kpxe4ypb4vk {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0;
		/* see note above */
	}

	.ldio-kpxe4ypb4vk div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
	</style>
	<div id="q"></div>
	<style>
	.flash {
		display: block;
		position: fixed;
		top: 125px;
		right: 25px;
		width: 350px;
		padding: 20px 25px 20px 85px;
		font-size: 16px;
		font-weight: 400;
		color: #66847C;
		background-color: #FFF;
		border: 2px solid #66847C;
		border-radius: 2px;
		box-shadow: 0 2px 5px rgba(0, 0, 0, 0.25);
		opacity: 0;
		z-index: 100;
		/*display:none;*/
	}

	.flash__icon {
		position: absolute;
		top: 50%;
		left: 0;
		width: 1.8em;
		height: 100%;
		padding: 0 0.4em;
		background-color: #66847C;
		color: #FFF;
		font-size: 36px;
		font-weight: 300;
		transform: translate(0, -50%);
	}

	.flash__icon .icon {
		position: absolute;
		top: 50%;
		transform: translate(0, -50%);
	}

	.button {
		position: absolute;
		top: 50%;
		left: 50%;
		padding: 10px 20px;
		border: 2px solid #66847C;
		border-radius: 2px;
		color: #66847C;
		transform: translate(-50%, -50%);
		transition: all 0.1s;
	}

	.button:hover {
		cursor: pointer;
		color: #FFF;
		background-color: #66847C;
	}

	.button:active {
		box-shadow: none;
		background-color: #5f7b74;
	}

	@-webkit-keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	@-moz-keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	@-o-keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	@keyframes drop-in-fade-out {
		0% {
			opacity: 0;
			visibility: visible;
			-webkit-transform: translate3d(0, -200%, 0);
			-moz-transform: translate3d(0, -200%, 0);
			-ms-transform: translate3d(0, -200%, 0);
			-o-transform: translate3d(0, -200%, 0);
			transform: translate3d(0, -200%, 0);
		}
		12% {
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		20% {
			opacity: 1;
		}
		70% {
			opacity: 1;
			visibility: visible;
			-webkit-transform: translate3d(0, 0, 0);
			-moz-transform: translate3d(0, 0, 0);
			-ms-transform: translate3d(0, 0, 0);
			-o-transform: translate3d(0, 0, 0);
			transform: translate3d(0, 0, 0);
		}
		80% {
			opacity: 0;
		}
		100% {
			visibility: hidden;
			-webkit-transform: translate3d(75%, 0, 0);
			-moz-transform: translate3d(75%, 0, 0);
			-ms-transform: translate3d(75%, 0, 0);
			-o-transform: translate3d(75%, 0, 0);
			transform: translate3d(25%, 0, 0);
		}
	}

	.animate--drop-in-fade-out {
		-webkit-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		-moz-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		-ms-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		-o-animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
		animation: drop-in-fade-out 3.5s 0.4s cubic-bezier(.32, 1.75, .65, .91);
	}
	</style>
	<?php include 'footer.php';?>