# Generated by Django 2.0.5 on 2019-05-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0003_visitorformdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorFormDetail',
        ),
    ]
