# Generated by Django 2.0.5 on 2019-06-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0004_delete_visitorformdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankusettingoptions',
            name='notes',
            field=models.CharField(default='Notes text', max_length=255),
        ),
        migrations.AlterField(
            model_name='thankusettingoptions',
            name='order_msg',
            field=models.CharField(default='Your order has been placed', max_length=255),
        ),
        migrations.AlterField(
            model_name='thankusettingoptions',
            name='rules_cancel_order',
            field=models.CharField(default='Rules for cancelling order', max_length=255),
        ),
    ]
