# Generated by Django 2.0.5 on 2019-07-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0005_auto_20190601_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='deposite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposite_given',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposite_taken',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='final_deposite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
