# Generated by Django 2.0.5 on 2019-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0006_auto_20190710_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deposite_given',
            new_name='deposite_collect',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deposite_taken',
            new_name='deposite_return',
        ),
        migrations.AddField(
            model_name='order',
            name='deposite_collect_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposite_return_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
