# Generated by Django 2.0.5 on 2019-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0007_auto_20190712_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bust_size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='hips_size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='waist_size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
