# Generated by Django 2.0.5 on 2019-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0008_auto_20190731_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_dt',
            field=models.DateTimeField(),
        ),
    ]
