# Generated by Django 2.0.5 on 2019-08-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0009_auto_20190809_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_dt',
            field=models.CharField(max_length=250),
        ),
    ]
