# Generated by Django 2.0.5 on 2019-09-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0011_auto_20190913_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='booking_dt',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
