# Generated by Django 2.0.5 on 2019-11-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0012_orderitem_booking_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_deposit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='depis_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deposite_collect_amount',
            field=models.IntegerField(blank=True, default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='return_deposit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='txnid_deposit_paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
