# Generated by Django 2.0.5 on 2018-12-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_setting', models.BooleanField(default=False)),
                ('product_setting', models.BooleanField(default=False)),
                ('ecom_config_setting', models.BooleanField(default=False)),
                ('user_address', models.BooleanField(default=False)),
                ('user_key', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecom_setting',
            },
        ),
        migrations.CreateModel(
            name='EcomSettingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_setting_option', models.IntegerField(default=0)),
                ('product_setting_option', models.IntegerField(default=0)),
                ('ecom_config_setting_option', models.CharField(max_length=255)),
                ('user_address_option', models.IntegerField(default=0)),
                ('user_key_option', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecom_option_setting',
            },
        ),
        migrations.CreateModel(
            name='EcomSettingSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecom_setting_step',
            },
        ),
    ]
